<?php
/**
 * Default configuration file for Sendy SMTP webhooks
 *
 * !!!! DO NOT EDIT THIS FILE !!!! 
 * Copy 'config.php.template' to 'config.php' and edit settings in 'config.php'
 *
 * @package    CristiContiu\SendySMTPWebhooks
 * @author     Cristi Contiu <cristi@contiu.ro>
 * @license    MIT
 * @link       https://github.com/cristi-contiu/sendy-smtp-webhooks
 */

// !!!! DO NOT EDIT THIS FILE !!!! 
// Copy 'config.php.template' to 'config.php' and edit settings in 'config.php'

return array_replace_recursive( array(

    /**
     * Configurations for available SMTP providers 
     * The keys are web-safe name of providers and are used in requests
     * @param array
     */
    'providers' => array (

        /**
         * Configurations for Mandrill SMTP provider
         * @param array
         */
        'mandrill' => array (

            /**
             * Webhook Key provided by Mandrill
             * Leave empty to disable Mandrill webhook authentication (will accept messages from other sources)
             * @param string
             */
            'webhookKey' => '',

            /**
             * Webhook URL EXACTLY as entered in Mandrill (including query parameters, if applicable)
             * Leave empty to disable Mandrill webhook authentication (will accept messages from other sources)
             * @param string
             */
            'webhookUrl' => '',

            /**
             * Provider class for Mandrill SMTP provider
             * @param string
             */
            'class' => 'CristiContiu\SendySMTPWebhooks\Providers\Mandrill',

        )
        
    ),

    /**
     * Number of soft bounces allowed before converting to hard bounce
     * @param integer
     */
    'sendyAllowedSoftBounces' => 3,

    /**
     * Path to Sendy config file - change only if you move script folder outside of sendy root
     * @param string
     */
    'sendyConfigFile' => '../includes/config.php',

    /**
     * Toggle debugging messages in log file
     * @param boolean
     */
    'debug' => false,

    /**
     * Application log file path
     * @param boolean
     */
    'logFile'  => 'app/app.log',

), (array) include __DIR__ . '/config.php');
